# Valeurs partagées entre les services db et wordpress : à modifier ici uniquement.
x-kiyose-db-name: &kiyose-db-name rkcxncpkiyose
x-kiyose-db-user: &kiyose-db-user wordpress
x-kiyose-db-password: &kiyose-db-password wordpress

services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpress
      MYSQL_DATABASE: *kiyose-db-name
      MYSQL_USER: *kiyose-db-user
      MYSQL_PASSWORD: *kiyose-db-password
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3
    volumes:
      - ./latelierkiyose:/var/www/html/wp-content/themes/latelierkiyose
      - ./uploads:/var/www/html/wp-content/uploads
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: *kiyose-db-user
      WORDPRESS_DB_PASSWORD: *kiyose-db-password
      WORDPRESS_DB_NAME: *kiyose-db-name
      WORDPRESS_TABLE_PREFIX: wp_akiy_
      WP_DEBUG: true
volumes:
  db_data: { }
